modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/Team-Resourceful/ResoucefulLib/issues/new/choose"

[[mods]]
    modId = "resourcefullib"
    version = "${version}"
    displayName = "Resourceful Lib"
    authors = "ThatGravyBoat, Epic_Oreo"
    description = "Team Resourceful Library"

[[mixins]]
    config = "resourcefullib.mixins.json"

[[dependencies.resourcefullib]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.5.3-beta,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefullib]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.5,)"
    ordering = "NONE"
    side = "BOTH"
